name: Push-from-Production-to-Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to Server on Production branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      # Install rsync
      - name: Install rsync
        run: sudo apt-get install -y rsync

      # Create the .ssh directory and add the SSH private key
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step for deploying files using rsync over SSH
      - name: Deploy files to Server using rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}

      # Step to build and restart the application
      - name: Run npm build and restart the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            npm install --force
            npm run build
            pm2 restart FunnelLiner-Custom-Domain
